log:
  level: debug
  disable_sentry: true

db:
  url: postgres://points:points@localhost:5432/points?sslmode=disable

listener:
  addr: localhost:8000

event_types:
  types:
    - name: passport_scan
      title: Points for passport scan
      reward: 5
      description: Get points for scan passport and share data
      short_description: Short description
      frequency: one-time
      action_url: https://...
      logo: https://...
      auto_claim: true
    - name: free_weekly
      title: Free weekly points
      reward: 1
      frequency: weekly
      description: Get free points every week by visiting the platform and claiming your reward
      short_description: Short description
    - name: be_referred
      title: Referral welcome bonus
      reward: 1
      frequency: one-time
      description: Be referred by a friend and get a welcome bonus
      short_description: Short description
      no_auto_open: true
    - name: referral_common
      reward: 1
      frequency: one-time
      title: Refer new users
      short_description: Refer friends and get a reward for each friend who verifies the passport
      description: Refer friends and get a reward for each friend who verifies the passport
    - name: referral_specific
      title: Refer user {:did}
      reward: 1
      frequency: unlimited
      description: The user {:did} has verified the passport. Claim the reward!
      short_description: Short description
      no_auto_open: true
      auto_claim: true
    - name: meetup_participation
      title: Prove your participation by scanning QR code
      reward: 5
      frequency: unlimited
      description: Prove your participation by scanning QR code
      short_description: Short description
      auto_claim: true
      qr_code_value: "qr_code_base64_string"

levels:
  levels:
    - lvl: 1
      threshold: 0
      referrals: 1
    - lvl: 2
      threshold: 10
      infinity: true

auth:
  addr: http://rarime-auth

verifier:
  verification_key_path: "./verification_key.json"
  allowed_age: 18
  allowed_identity_timestamp: 1715698750

root_verifier:
  rpc: evm_rpc_url
  contract: registration_contract_address
  request_timeout: 10s

sig_verifier:
  verification_key: "37bc75afc97f8bdcd21cda85ae7b2885b5f1205ae3d79942e56457230f1636a037cc7ebfe42998d66a3dd3446b9d29366271b4f2bd8e0d307db1d320b38fc02f"
