log:
  level: debug
  disable_sentry: true

db:
  url: postgres://points:points@geo-points-db:5432/points?sslmode=disable

listener:
  addr: :80

event_types:
  types:
    - name: passport_scan
      title: Points for passport scan
      reward: 10
      description: Get points for scan passport and share data
      short_description: Short description
      frequency: one-time
      action_url: https://...
      logo: https://...
      auto_claim: true
    - name: free_weekly
      title: Free weekly points
      reward: 1
      frequency: weekly
      description: Get free points every week by visiting the platform and claiming your reward
      short_description: Short description
    - name: be_referred
      title: Referral welcome bonus
      reward: 1
      frequency: one-time
      description: Be referred by a friend and get a welcome bonus
      short_description: Short description
      no_auto_open: true
    - name: referral_common
      reward: 1
      frequency: one-time
      title: Refer new users
      short_description: Refer friends and get a reward for each friend who verifies the passport
      description: Refer friends and get a reward for each friend who verifies the passport
    - name: referral_specific
      title: Refer user {:did}
      reward: 1
      frequency: unlimited
      description: The user {:did} has verified the passport. Claim the reward!
      short_description: Short description
      no_auto_open: true
      auto_claim: true
    - name: meetup_participation
      title: Prove your participation by scanning QR code
      reward: 5
      frequency: unlimited
      description: Prove your participation by scanning QR code
      short_description: Short description
      auto_claim: true
      qr_code_value: "aawdiojawndgawjhkdla"

levels:
  levels:
    - lvl: 1
      threshold: 0
      referrals: 10
    - lvl: 2
      threshold: 10
      infinity: true

auth:
  addr: http://geo-auth

verifier:
  verification_key_path: "./verification_key.json"
  allowed_age: 18
  allowed_identity_timestamp: 1715698750

root_verifier:
  rpc: https://rpc.evm.node1.mainnet-beta.rarimo.com:443
  contract: 0x59123B0D0f95EB23183879f476B6939cEFd2cF3B
  request_timeout: 10s

sig_verifier:
  verification_key: "bcb14d08dc1472b80f49eaf72f0873ac314a7146083bbf3694df8c3238949f2ec0971427f5509382a2812c700e541e328cd6ec65a1383c3ca435cdf55862dc4b"
