log:
  level: debug
  disable_sentry: true

db:
  url: postgres://auth:auth@geo-auth-db:5432/auth?sslmode=disable

listener:
  addr: :80

jwt:
  secret_key: 0xbcb14d08dc1472b80f49eaf72f0873ac314a7146083bbf3694df8c3238949f2ec0971427f5509382a2812c700e541e328cd6ec65a1383c3ca435cdf55862dc4b
  access_expiration_time: 1h
  refresh_expiration_time: 72h

cookies:
  domain: "*"
  secure: true
  same_site: 4

auth_verifier:
  verification_key_path: "./auth_verification_key.json"
  disabled: true

passport_verifier:
  verification_key_path: "./passport_verification_key.json"
  allowed_age: 18
  allowed_identity_timestamp: 1715698750

root_verifier:
  rpc: https://rpc.evm.node1.mainnet-beta.rarimo.com:443
  contract: 0x59123B0D0f95EB23183879f476B6939cEFd2cF3B
  request_timeout: 10s

sig_verifier:
  verification_key: "bcb14d08dc1472b80f49eaf72f0873ac314a7146083bbf3694df8c3238949f2ec0971427f5509382a2812c700e541e328cd6ec65a1383c3ca435cdf55862dc4b"

points:
  admin: 0x8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
  url: http://geo-points
  default_verified: true
  disabled: true